In [1]:
import numpy as np 
from numpy import linalg as LA 
# np.set_printoptions(precision=2)

Y = np.array([[5, 5, 0, 0, 1, 1], [5, 4, 1, 0, 1, 0], [4, 4, 1, 0, 0, 1], \
             [1, 1, 4, 4, 4, 5], [1, 0, 5, 4, 5, 4]], dtype = np.float32)

U, S, V = LA.svd(Y)

print U

[[-0.35544589 -0.53119844  0.26212287  0.6439572   0.32878131]
 [-0.3287476  -0.47151235 -0.56767344 -0.03909239 -0.58806443]
 [-0.29696101 -0.41328034  0.24235058 -0.76390344  0.31421527]
 [-0.57911378  0.35758358  0.54515773  0.00330032 -0.4894419 ]
 [-0.58482873  0.44366392 -0.50309813  0.01521448  0.45584917]]


In [2]:
print S

[ 13.51996326  10.01233768   1.71215713   0.99940604   0.18275633]


In [3]:
print V

[[ -4.26979989e-01  -3.59407604e-01  -4.33899641e-01  -3.44362617e-01
   -4.38225478e-01  -4.35451686e-01]
 [ -5.85820019e-01  -5.83038628e-01   2.76045561e-01   3.20104092e-01
    2.64268279e-01   2.61486888e-01]
 [ -3.01544100e-01   3.23849201e-01  -3.85585278e-01   9.82610807e-02
   -3.74037087e-01   7.11307168e-01]
 [ -1.27824713e-02   1.11096296e-02  -7.14146376e-01   7.41031915e-02
    6.94550991e-01  -4.26120497e-02]
 [ -4.00245517e-01   3.23205590e-01   2.60615349e-01  -7.35246181e-01
    3.40317279e-01   1.04969107e-01]
 [  4.72455591e-01  -5.66946685e-01  -9.44911167e-02  -4.72455591e-01
   -1.91419070e-15   4.72455591e-01]]


In [4]:
Y = np.array([[1, 1, 1, 0, 0], 
              [3, 3, 3, 0, 0], 
              [4, 4, 4, 0, 0], 
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4], 
              [0, 0, 0, 5, 5], 
              [0, 1, 0, 2, 2]])

U, S, VT = LA.svd(Y)

In [5]:
print U


[[ -1.37599126e-01  -2.36114514e-02  -1.08084718e-02   3.05093008e-01
    4.07157532e-01  -7.68530391e-01  -3.61793030e-01]
 [ -4.12797378e-01  -7.08343543e-02  -3.24254153e-02   8.34728309e-01
   -2.97923856e-02   3.20992463e-01   1.51110271e-01]
 [ -5.50396503e-01  -9.44458057e-02  -4.32338870e-02  -1.70311198e-01
   -7.42781963e-01  -2.93933286e-01  -1.38371905e-01]
 [ -6.87995629e-01  -1.18057257e-01  -5.40423588e-02  -4.25606628e-01
    5.30669495e-01   1.96257229e-01   9.23899672e-02]
 [ -1.52775087e-01   5.91100963e-01   6.53650843e-01   3.71510662e-17
   -7.36025541e-17   1.90478975e-01  -4.04620513e-01]
 [ -7.22165140e-02   7.31311857e-01  -6.78209218e-01   3.55502015e-17
   -1.17370084e-16  -2.31655434e-17  -4.37229973e-18]
 [ -7.63875433e-02   2.95550482e-01   3.26825421e-01   1.85755331e-17
   -6.45568527e-17  -3.80957951e-01   8.09241027e-01]]


In [6]:
print S

[  1.24810147e+01   9.50861406e+00   1.34555971e+00   2.88432683e-16
   9.30818781e-33]
